name: JoinCommand
main: co.kohle.JoinCommand.JoinCommand
author: AmazingKohle
version: 2.2
permissions:
  joincommand.every:
    description: Gives permission for the every join commands to be executed for that player.
    default: true
  joincommand.first:
    description: Gives permission for the first join commands to be executed for that player.
    default: true